project:
  type: website
  output-dir: docs

website:
  title: "OCEPTX"
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
      - text: "Research"
        menu:
        - text: "Driving While Intoxicated (DWI)"
      - text: "Contact Author"
        href: https://mattduran12.github.io

format:
  html:
    theme: cosmo
    css: styles2.css
    toc: false

editor: source

  